imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false
    validation:
       cache: validator.mapping.cache.apc
    serializer:
       cache: serializer.mapping.cache.apc

doctrine:
   orm:
       metadata_cache_driver: apc
       result_cache_driver: apc
       query_cache_driver: apc

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
