bpeh_nestable_page:
    resource: "@BpehNestablePageBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# Sonata media routing
gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /%admin_path%/media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /%admin_path%/media

# FOS user bundle default routing
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

# fos_user_profile:
#     resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#     prefix: /profile

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

# fos_user_change_password:
#     resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
#     prefix: /profile

# sonata admin
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /%admin_path%

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /%admin_path%
